set(_CATKIN_CURRENT_PACKAGE "my_drone")
set(my_drone_VERSION "0.0.0")
set(my_drone_MAINTAINER "uav <uav@todo.todo>")
set(my_drone_PACKAGE_FORMAT "2")
set(my_drone_BUILD_DEPENDS "mavros" "mavros_msgs" "cv_bridge" "geometry_msgs" "message_filters" "nav_msgs" "pcl_conversions" "pcl_ros" "rospy" "roscpp" "sensor_msgs" "tf2" "tf2_ros" "std_msgs" "livox_ros_driver2")
set(my_drone_BUILD_EXPORT_DEPENDS "mavros" "mavros_msgs" "cv_bridge" "geometry_msgs" "message_filters" "nav_msgs" "pcl_conversions" "pcl_ros" "rospy" "roscpp" "sensor_msgs" "tf2" "tf2_ros" "std_msgs" "livox_ros_driver2")
set(my_drone_BUILDTOOL_DEPENDS "catkin")
set(my_drone_BUILDTOOL_EXPORT_DEPENDS )
set(my_drone_EXEC_DEPENDS "mavros" "mavros_msgs" "cv_bridge" "geometry_msgs" "message_filters" "nav_msgs" "pcl_conversions" "pcl_ros" "rospy" "roscpp" "sensor_msgs" "tf2" "tf2_ros" "std_msgs" "livox_ros_driver2")
set(my_drone_RUN_DEPENDS "mavros" "mavros_msgs" "cv_bridge" "geometry_msgs" "message_filters" "nav_msgs" "pcl_conversions" "pcl_ros" "rospy" "roscpp" "sensor_msgs" "tf2" "tf2_ros" "std_msgs" "livox_ros_driver2")
set(my_drone_TEST_DEPENDS )
set(my_drone_DOC_DEPENDS )
set(my_drone_URL_WEBSITE "")
set(my_drone_URL_BUGTRACKER "")
set(my_drone_URL_REPOSITORY "")
set(my_drone_DEPRECATED "")